package com.example.domain.usecase.reminder

import com.example.domain.base.BaseUseCase
import com.example.domain.model.app.AppResult
import com.example.domain.model.app.DataError
import com.example.domain.model.reminder.Reminder
import com.example.domain.repository.IRemindersRepository
import kotlinx.coroutines.CoroutineDispatcher
data class AddReminderParams(
    val userId: String,
    val vehicleId: String,
    val title: String,
    val dueDateMillis: Long,
    val note: String? = null,
)

class AddReminderUseCase(
    dispatcher: CoroutineDispatcher,
    private val repository: IRemindersRepository
) : BaseUseCase<AddReminderParams, Reminder>(dispatcher) {

    override suspend fun execute(params: AddReminderParams): AppResult<Reminder> {
        if (params.userId.isBlank() || params.vehicleId.isBlank() || params.title.isBlank() || params.dueDateMillis <= 0L) {
            return AppResult.Failure(DataError.Local.ValidationError)
        }

    return repository.addReminder(
        Reminder(
            id = "", // ID will be generated by the repository
            userId = params.userId,
            vehicleId = params.vehicleId,
            title = params.title,
            dueDateMillis = params.dueDateMillis,
            note = params.note
        )
    )
}
}